# Generated by Django 4.0.5 on 2023-12-09 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_delete_queries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='querylog',
            name='category',
        ),
        migrations.RemoveField(
            model_name='querylog',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='querylog',
            name='status',
        ),
        migrations.RemoveField(
            model_name='querylog',
            name='user_id',
        ),
        migrations.AddField(
            model_name='querylog',
            name='imageResponse',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='querylog',
            name='answer_text',
            field=models.TextField(default='A'),
        ),
        migrations.AlterField(
            model_name='querylog',
            name='query_id',
            field=models.AutoField(auto_created=True, default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='querylog',
            name='query_text',
            field=models.TextField(default='Q'),
        ),
    ]
