# Generated by Django 4.0.5 on 2023-12-09 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_querylog_category_remove_querylog_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querylog',
            name='query_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
