# Generated by Django 5.0 on 2024-01-07 03:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0005_alter_querylog_query_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="querylog",
            name="user",
            field=models.TextField(default="-"),
        ),
    ]
