# Generated by Django 5.0 on 2024-01-07 03:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0006_querylog_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="ErrorLog",
            fields=[
                ("error_id", models.AutoField(primary_key=True, serialize=False)),
                ("error_text", models.TextField(default="E")),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("user", models.TextField(default="-")),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_name", models.TextField(default="u")),
            ],
        ),
    ]
