# Generated by Django 5.0 on 2024-01-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0008_delete_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="asha_files")),
            ],
        ),
    ]
