# Generated by Django 5.0 on 2024-01-11 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0009_filemodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filemodel",
            name="file",
            field=models.FileField(upload_to="asha_uploaded_files"),
        ),
    ]
