# Generated by Django 5.0 on 2024-01-11 19:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0010_alter_filemodel_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="filemodel",
            name="uploaded_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
