# Generated by Django 4.0.5 on 2023-12-09 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_created_queries_timestamp_remove_queries_id_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Queries',
        ),
    ]
